# Generated by Django 5.1.2 on 2024-10-22 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subclub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclub_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=255)),
                ('trip_date', models.DateField()),
                ('trip_description', models.TextField()),
                ('trip_leader', models.CharField(max_length=255)),
                ('trip_capacity', models.IntegerField()),
                ('subclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subclub')),
            ],
        ),
        migrations.CreateModel(
            name='TripRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.trip')),
            ],
        ),
    ]
